require:
    - rubocop-rails

	inherit_from:
    - config/rubocop/rubocop.yml
    - config/rubocop/rails.yml
    - config/rubocop/rspec.yml
    - .rubocop_todo.yml

	AllCops:
	  TargetRubyVersion: 2.6